env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends: standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  semi:                         [ 2, never ]
  comma-dangle:                 [ 2, always-multiline ]
  space-before-function-paren:  [ 2, never ]
  quotes:                       0
  comma-spacing:                0